'use strict';
const fs=require('node:fs'),assert=require('node:assert/strict'),crypto=require('node:crypto'),path=require('node:path');
// Run from the Site checkout, or pass its absolute path as the first argument.
const base=path.resolve(__dirname,'..'),J=require(path.join(base,'dist','joint.js')),C=require(path.join(base,'dist','core.js')),R=require(path.join(base,'dist','research.js'));let checks=[];
const check=require('node:test'); function close(a,b,t=2e-12){assert.ok(Math.abs(a-b)<=t,`${a} != ${b}`)}
const components=[.2,.3,.5].map((p,c)=>({probability:p,weights:Array.from({length:45},(_,i)=>.5+((i*13+c*7)%17)/10)}));const options={fixed:[4,1,3,2],excluded:Array.from({length:33},(_,i)=>i+13)};
const space=J.mixtureSpace(components,options),tickets=[];for(let a=5;a<=12;a++)for(let b=a+1;b<=12;b++)tickets.push([1,2,3,4,a,b]);
const expected=tickets.map(t=>components.reduce((acc,c)=>acc+c.probability*c.weights[t[4]-1]*c.weights[t[5]-1]/tickets.reduce((z,v)=>z+c.weights[v[4]-1]*c.weights[v[5]-1],0),0));
check('28 constrained mixture probabilities equal independently normalized pair-product enumeration',()=>{assert.equal(space.total,28);tickets.forEach((t,i)=>close(Math.exp(space.logProbability(t)),expected[i]));close(expected.reduce((a,b)=>a+b,0),1)});
check('marginals agree with full constrained enumeration; fixed1 excluded0 sum6',()=>{const m=space.marginals();for(let n=1;n<=45;n++)close(m[n-1],tickets.reduce((s,t,i)=>s+(t.includes(n)?expected[i]:0),0));close(m.reduce((a,b)=>a+b,0),6)});
check('invalid, fixed-missing and excluded-including tickets have zero probability',()=>{for(const t of [[1,1,2,3,4,5],[1,2,3,5,6,7],[1,2,3,4,5,13],[1,2,3,4,5],[1,2,3,4,5,46]])assert.equal(space.logProbability(t),-Infinity)});
check('fixed six has exactly one combination and probability1 even with excluded remainder',()=>{const t=[6,5,4,3,2,1],s=J.mixtureSpace(components,{fixed:t,excluded:Array.from({length:39},(_,i)=>i+7)});assert.equal(s.total,1);close(s.logProbability(t),0);assert.deepEqual(s.sample(()=>.37),[1,2,3,4,5,6]);assert.deepEqual(J.generateMixture(components,{fixed:t},1,[],()=>.5).numbers,[[1,2,3,4,5,6]]);assert.throws(()=>J.generateMixture(components,{fixed:t},1,[t]))});
check('tiny-space blocked duplicates and out-of-space rows counted correctly; exhaustion gives unique valid results',()=>{const blocked=[tickets[0],[...tickets[0]].reverse(),[1,2,3,4,5,13],...tickets.slice(1,9)];const out=J.generateMixture(components,options,19,blocked,R.seededRandom(798));assert.equal(out.available,19);assert.equal(out.numbers.length,19);assert.equal(new Set(out.numbers.map(C.key)).size,19);out.numbers.forEach(t=>{assert.ok(tickets.some(x=>C.key(x)===C.key(t)));assert.ok(!blocked.some(x=>C.key(x)===C.key(t)))});assert.throws(()=>J.generateMixture(components,options,20,blocked));});
check('invalid constraints and unsupported sum/odd settings reject',()=>{for(const opts of [{fixed:[1,1]},{fixed:[1],excluded:[1]},{fixed:[1,2,3,4,5,6,7]},{minSum:21},{maxOdd:6}])assert.throws(()=>J.mixtureSpace(components,opts));assert.throws(()=>J.generateMixture(components,{excluded:Array.from({length:40},(_,i)=>i+6)},1));});
let sampleError;
check('100000 seeded mixture samples agree with exact constrained probabilities',()=>{const sampleRng=R.seededRandom(71238),counts=new Map(tickets.map(t=>[C.key(t),0])),N=100000;for(let i=0;i<N;i++){const k=C.key(space.sample(sampleRng));assert.ok(counts.has(k));counts.set(k,counts.get(k)+1)}sampleError=Math.max(...tickets.map((t,i)=>Math.abs(counts.get(C.key(t))/N-expected[i])));assert.ok(sampleError<.0035)});
check('large-space rejection generation returns20 unique valid unblocked games',()=>{const out=J.generateMixture(components,{},20,[[1,2,3,4,5,6]],R.seededRandom(981));assert.equal(out.numbers.length,20);assert.equal(new Set(out.numbers.map(C.key)).size,20);out.numbers.forEach(t=>{assert.ok(C.validNumbers(t,6));assert.notEqual(C.key(t),'1-2-3-4-5-6')})});
check('extreme common scaling preserves sampler marginals and logProbability',()=>{const t=[1,2,3,4,5,6];let baseline;for(const factor of [1,1e100,1e-300]){const s=J.componentSpace(Array(45).fill(factor)),m=s.marginals();m.forEach(p=>close(p,6/45));close(s.logProbability(t),-Math.log(8145060));const draw=s.sample(R.seededRandom(17));if(baseline)assert.deepEqual(draw,baseline);else baseline=draw}});
check('accepted near-unit mixing shares are normalized exactly for probability marginals and sampling',()=>{for(const p of [1-5e-10,1+5e-10]){const s=J.mixtureSpace([{probability:p,weights:Array(45).fill(1)}],options);close(tickets.reduce((v,t)=>v+Math.exp(s.logProbability(t)),0),1);close(s.marginals().reduce((a,b)=>a+b,0),6);assert.equal(s.logProbability(tickets[0]),s.logProbability(tickets.at(-1)))}});
check('unsupported weight ratios reject explicitly; accepted1e-50 boundary stays finite',()=>{const low=Array(45).fill(1e-51);low[0]=1;assert.throws(()=>J.componentSpace(low));const boundary=low.map(x=>x===1?x:1e-50),s=J.componentSpace(boundary),m=s.marginals();assert.ok(m.every(Number.isFinite));close(m.reduce((a,b)=>a+b,0),6,2e-11);assert.ok(Number.isFinite(s.logProbability([2,3,4,5,6,7])));assert.ok(C.validNumbers(s.sample(R.seededRandom(15)),6))});
check('fixed and excluded extreme weights cancel from conditional probability',()=>{const a=components.map(c=>({...c,weights:c.weights.slice()})),b=components.map(c=>({...c,weights:c.weights.slice()}));for(const c of b){for(const n of options.fixed)c.weights[n-1]=1e250;for(const n of options.excluded)c.weights[n-1]=1e-250}const s1=J.mixtureSpace(a,options),s2=J.mixtureSpace(b,options);tickets.forEach(t=>close(s1.logProbability(t),s2.logProbability(t)));assert.deepEqual(s1.sample(R.seededRandom(29)),s2.sample(R.seededRandom(29)))});
