'use strict';
const fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),a=require('../data/analysis.json'),v=require('../data/validation.json'),d=require('../data/draws.json');
const selected=v.models.find(m=>m.id===v.selectedModel),h=selected.holdout;
const pct=x=>(100*x).toFixed(4)+'%';
const lines=[
'# 최근 10년 로또 분석 및 생성기 검증',
'',
'## 결론',
'',
`공식 ${d.draws.length}회 기록을 새로 수집했으며 엑셀을 분석·생성의 입력으로 사용하지 않았다. 번호별 빈도와 번호 쌍의 출현 차이는 각각 다중 비교 보정 후 유의하지 않았다. 개발 구간에서 선택한 **${v.selectedLabel}** 모형의 최종 ${h.count}회 오차 개선 신뢰구간은 0을 포함했다. 미래 당첨 확률을 극도로 높이는 예측력은 확인되지 않았다.`,
'',
'실제로 계산 가능한 개선은 여러 게임의 번호 분산이다. 완전 비중복 5게임의 5등 이상 확률은 11.8679%, 균등하게 고른 서로 다른 무작위 5게임 평균은 11.3624%로 차이는 +0.5056%p다. 1등 확률과 기대 당첨금이 함께 커지는 것은 아니다.',
'',
'## 자료와 출처',
'',
`요청 기간 ${d.metadata.requestedStartDate}~${d.metadata.requestedEndDate}. 실제 추첨은 ${d.draws[0].round}회(${d.draws[0].date})~${d.draws.at(-1).round}회(${d.draws.at(-1).date}), 총 ${d.draws.length}회이며 누락은 0회다. 모든 행을 공식 원본과 다시 대조하고 원본 54개 파일의 해시를 확인했다. 본번호와 보너스를 분리했다.`,
'',
'[동행복권 공식 결과](https://m.dhlottery.co.kr/lt645/result) 페이지가 사용하는 공개 API로 수집했다. 정규화 자료는 `data/draws.json`, 보존한 응답은 `data/raw/`, 요청 주소·크기·SHA256은 `data/source-manifest.json`에 있다.',
'',
`자료 SHA256: ${a.independentValidation.datasetSha256}`,
'',
'## 45개 번호의 상세 통계',
'',
'한 번호의 본번호 포함 확률은 공정한 추첨에서 6/45다. 전체 기간의 번호별 기대 출현 횟수는 69.6회다. 현재 공백은 마지막 출현 후 완료된 추첨 수, 최장 완결 공백은 관찰 구간 안의 두 출현 사이에 있었던 연속 미출현 회차 수다. 관찰 구간 끝의 진행 중 공백이나 시작 전 기간을 전체 길이가 알려진 공백처럼 취급하지 않았다.',
'',
'| 번호 | 전체 | 최근52 | 최근156 | 현재 공백 | 최장 완결 공백 | 보너스 | 보정 p |',
'|---:|---:|---:|---:|---:|---:|---:|---:|',
...a.numberFrequency.map(n=>`| ${n.number} | ${n.count} | ${n.recent52Count} | ${n.recent156Count} | ${n.currentGap} | ${n.maximumCompletedGap} | ${n.bonusCountSeparately} | ${n.bonferroni45AdjustedP.toFixed(3)} |`),
'',
`번호별 정확 양측 이항 검정에 Bonferroni 45개 보정을 적용했다. 보정 후 유의한 번호는 ${a.frequencyUniformity.numberTestsSignificantAfterBonferroni45.length}개다. 전체 빈도 χ² 통계는 한 추첨 안에서 같은 번호를 두 번 뽑지 않는 공분산을 반영해 Pearson 통계에 44/39를 곱했다. 결과 ${a.frequencyUniformity.correctedQ.toFixed(4)}, 자유도44, 근사 p=${a.frequencyUniformity.asymptoticChiSquaredP.toFixed(5)}다. 유의하지 않음은 장비의 완전한 공정성이 입증되었다는 뜻은 아니다.`,
'',
'## 동반 출현과 패턴',
'',
'번호 쌍의 기대 동반 출현 확률은 1/66이며 전체 기간 기대 횟수는 7.9091회다. 990쌍 중 상위15쌍을 아래에 표시한다. 순위를 고른 후의 우연한 극단값을 고려해 990개 보정 p를 제시한다.',
'',
'| 번호 쌍 | 동반 출현 | 990개 보정 p |','|---|---:|---:|',
...a.pairCooccurrence.top15.map(p=>`| ${p.numbers.join('·')} | ${p.count} | ${p.bonferroni990AdjustedP.toFixed(4)} |`),
'',
`연속 번호가 하나 이상 나온 회차는 ${a.consecutive.drawsWithAtLeastOneConsecutivePair}/${d.draws.length} (${pct(a.consecutive.observedRate)}). 이론은 1−C(40,6)/C(45,6)=${pct(a.consecutive.theoreticalRate)}다.`,
'',
`본번호 합계 평균은 ${a.sum.mean.toFixed(4)}, 표준편차는 ${a.sum.sampleStandardDeviation.toFixed(4)}다. 이론 평균138, 표준편차√897≈29.9500이다. 실제 최소·최대는 ${a.sum.minimumObserved}·${a.sum.maximumObserved}다. 흔한 합계 범주에 조합이 많이 속한다는 사실이 개별 조합의 당첨 확률을 높이지 않는다.`,
'',
'| 홀수 개수 | 관측 횟수 | 무작위 기대 횟수 |','|---:|---:|---:|',
...a.oddNumberCount.distribution.map(r=>`| ${r.value} | ${r.count} | ${r.expectedCount.toFixed(3)} |`),
'',
'홀수 분포: C(23,k)·C(22,6−k)/C(45,6).',
'',
'| 직전 회차와 같은 번호 수 | 관측 횟수 | 무작위 기대 횟수 |','|---:|---:|---:|',
...a.previousDrawRepeats.distribution.map(r=>`| ${r.value} | ${r.count} | ${r.expectedCount.toFixed(3)} |`),
'',
`요청 구간 안의 연속된 ${a.previousDrawRepeats.transitionCount}쌍만 집계했다. 이론 C(6,k)·C(39,6−k)/C(45,6), 기대 중복수0.8개다. 연도별 분석은 부분 연도2016년16회·2026년37회를 표시하고 색상을 연도 내 출현 비율로 계산한다.`,
'',
'## 예측 모형의 시간 순서 검증',
'',
`첫 ${v.protocol.warmup}회는 준비, 다음 ${v.protocol.development}회는 모형 선택, 마지막 ${v.protocol.holdout}회(${h.firstRound}~${h.lastRound}회, ${h.firstDate}~${h.lastDate})는 최종 검증이다. 각 회차마다 이전 자료만 사용했다. 프로토콜·모형은 성능 계산 전에 코드로 고정했고 선택은 개발 구간의 최소 Brier 오차만 사용했다. 공개된 데이터를 가린 회고검증이며 실제 미래에 시행한 사전 등록 실험은 아니다.`,
'',
'모형: 균등, 최근52회 빈도, 최근156회 빈도, 최근52회 저빈도, 최근156회 자료의 반감기26회 지수가중. 빈도와 흐름에는 20회분 균등 사전값을 섞었다. 저빈도 가중치의 원재료는 (6/39)·(1−보정52회빈도)다. 이 값들은 티켓의 선택 가중치이고 실제 미래 확률이 아니다. 조합 확률은 선택된 6개 가중치 곱에 비례하며, 이 분포의 정확한 포함 확률을 기본대칭다항식으로 계산하여 생성과 검증을 일치시켰다.',
'',
'Brier=45개 번호에 대한 (모형 포함확률−실제 출현 여부)²의 평균. 낮을수록 좋다. 균등 기준은 회차마다 정확히26/225다.',
'',
'| 모형 | 선택 구간 Brier | 최종 Brier | 최종 개선량 | 98.75% 개선 구간 |','|---|---:|---:|---:|---|',
...v.models.map(m=>`| ${m.label} | ${m.development.brier.toFixed(8)} | ${m.holdout.brier.toFixed(8)} | ${m.holdout.improvement.toFixed(8)} | ${m.holdout.improvementCI9875.map(x=>x.toFixed(8)).join(' ~ ')} |`),
'',
`선택 모형 ${v.selectedLabel}의 95% 개선 구간은 ${h.improvementCI95.map(x=>x.toFixed(8)).join(' ~ ')}다. 0을 포함하므로 최종 우세 판정은 ${v.selectedHoldoutSupportsAdvantage?'관찰됨':'미확인'}이다. 대안4개를 함께 볼 때는 각98.75% 구간을 사용한다. 회차4개 블록으로4,000번 원형 블록 부트스트랩을 시행한 근사 구간이며 엄밀한 유한표본 보장을 뜻하지 않는다.`,
'',
'| 5게임 묶음 | 선택 구간 5등 이상 하나라도 | 최종 구간 |','|---|---:|---:|',
...v.models.map(m=>`| ${m.label} | ${pct(m.development.anyPrizeRate)} | ${pct(m.holdout.anyPrizeRate)} |`),
'',
'가중 모형은 각 회차마다 재현 가능한256개 시드로 서로 다른5조합을 생성한 Monte Carlo 추정이다. 균등 기준은 정확한 이론 평균이다. 반복 시드는 같은 추첨 결과에 대한 생성 변동성을 보여주며, 검증 회차 수를 늘리지 않는다. 고정·제외가 없는 기본 모형의 검증으로, 사용자 조건이 추가된 조합에 성적을 그대로 적용할 수 없다.',
'',
'## 분산 조합의 정확한 확률',
'',
'전체 추첨 결과 M=C(45,6)=8,145,060. 한 티켓이3개 이상 맞는 결과 K=Σ(j=3..6)C(6,j)C(39,6−j)=194,130. 서로 다른5조합을 균등하게 고르는 평균 성공 확률은 1−∏(i=0..4)(M−K−i)/(M−i)=11.36235733%. 번호가 완전히 겹치지 않는5게임은 [5K−C(5,2)·C(6,3)²]/M=11.86792976%. 이때3게임이 동시에3개 이상 맞는 경우는 없으므로 쌍 교집합까지 빼면 정확하다.',
'',
'임의 조합은 각 티켓이3~6개 맞는 추첨 결과를 열거하고, 정렬된 번호 a1<…<a6에 순번 Σ(r=1..6)C(ar−1,r)를 부여해 비트셋으로 합집합 크기를 센다. 같은 당첨 결과는 한 번만 집계한다. 보너스는2·3등을 나누지만5등 이상 여부(본번호3개 이상)에는 영향을 주지 않는다. 최대20게임까지 계산한다.',
'',
'기본 분산 생성은 가능한 경우 서로 다른30개 번호로5조합을 만든다. 고정 번호·후보 부족 등으로 불가능하면 게임 간 겹침의 세제곱 합을 줄이는 제한된 탐색을 사용한다. 이 점수는 확률이 아니며 전역 최적성을 보장하지 않는다. 표시 확률은 점수를 변환한 것이 아니라 실제 결과 합집합으로 다시 계산한 값이다.',
'',
'## 재현성과 한계',
'',
'기존18개 자동 검사에서 조합·확률·모형 분포·원본 해시·과거 점수 재계산을 확인했다. 별도 독립 알고리즘인 상태 DP로 겹침0~6개의2티켓 및 임의3·5티켓의 당첨 영역을 검산했고,1,830개 과거 Brier 행도 다시 계산했다. 번호/쌍 보정 가족은 별개이며 다른 기간·패턴 결과는 탐색적이다. 과거 차이와 검정 결과만으로 추첨 기계의 공정성이나 미래 편향을 확정할 수 없다.',
'',
'연결된 브라우저가 없어 실제 화면 조작 및 선택적 WebMCP 도구는 자동 확인하지 못했다. 오프라인 실행 파일의 JavaScript 구문·참조 요소·데이터 일치·구성은 확인했다.',
'',
'## 방법론 출처',
'',
...v.references.map(r=>`- [${r.title}](${r.url})`),''
];
fs.writeFileSync(path.join(root,'ANALYSIS.md'),lines.join('\n'));
